### DISCUSSION TITLE
Get ranges in graphemes or codepoints?

### DISCUSSION THREAD

**Discussion by tom-sherman** [facebook/lexical#6432] [Q&A]
Is there a way to get lexical to give the start and end offsets of nodes in graphemes instead of bytes?

I want to transform the data from the editor to an offset based system that looks something like this:

```yml
text: "emoji link: 👀"
facets:
  - type: bold
    start: 0
    end: 11
  - type: link
    start: 12
    end: 13 # Note, not 14! We're offsetting by graphemes not bytes
    href: example.com
````

Which would render something akin to the following markdown: `**emoji link:** [👀](example.com)`

Failing that, does lexical expose codepoints? That's my backup option right now.
