### ISSUE TITLE
Feature: Support for inline image nodes

### ISSUE THREAD

**Issue by HexM7** [facebook/lexical#2512]
It would be nice to have support for inline images as they allow for more detailed and emphasized text:

![Screenshot (45)](https://user-images.githubusercontent.com/77036902/175778688-007f368d-6353-4679-8c5d-375d413f0478.png)

This would also allow us to have images inside table rows or columns as such:

![Screenshot (46)](https://user-images.githubusercontent.com/77036902/175778686-fb00e1a1-c221-486f-96b4-e51dbc14dcb0.png)

This is currently supported on Froala editor:
[Example](https://froala.com/wysiwyg-editor/examples/image-styles/)

![Screenshot (47)](https://user-images.githubusercontent.com/77036902/175778709-7b64faab-e628-4a97-823b-ffef5e698bd7.png)

This could be done using CSS:

```css
span[data-picture-align="left"] img {
    margin-right: 20px;
    float: left;
}

span[data-picture-group="right"] img {
    margin-left: 20px;
    float: right;
}

/* Make image take entire width on smaller screens */
@media all and (max-width: ...) {
  ...
}
```

## More resources:
- [Drupal](https://www.drupal.org/node/1983312)
