### ISSUE TITLE
Bug: Page's scrollbar jumps to the bottom of the editor when contents exceed editor's height

### ISSUE THREAD

**Issue by mnemyx** [facebook/lexical#3323]
Lexical version: 0.4.1

## Steps To Reproduce

1. Create a `ContentEditable` with a `className` value
2. The CSS contains a `max-height` OR `height` value
3. Page itself has a scrollbar 
4. Hit enter in the editor until a scrollbar appears

![chrome_MmRtDMwE3T](https://user-images.githubusercontent.com/770706/200424771-9b52fc91-0a15-40fc-99ad-a854c28c9ecc.gif)

![chrome_AoQVZuFmwS](https://user-images.githubusercontent.com/770706/200424276-8cd5b12b-8d59-4b88-9be3-49905516e84b.gif)

Link to code example:

```javascript
<LexicalComposer initialConfig={editorConfig}>
    <div className={styles["editor-container"]}>
        <ToolbarPlugin/>
        <div className={styles["editor-inner"]}>
            <RichTextPlugin
                contentEditable={<ContentEditable className={styles["editor-input"]}/>}
                placeholder={<Placeholder/>}
            />
            <OnChangePlugin onChange={onChange}/>
            <HistoryPlugin/>
            <ListPlugin />
            {/*<AutoScrollPlugin scrollRef={scrollRef}/>*/}
            <InitialStatePlugin initalState={props.initialState}/>
        </div>
    </div>
</LexicalComposer>
```

where the CSS style is:

```css
.editor-input {
  min-height: 150px;
  max-height: 150px;
  overflow-y: auto;
  resize: vertical;
  font-size: 15px;
  position: relative;
  tab-size: 1;
  outline: 0;
  padding: 15px 10px;
  caret-color: #444;
  border: 1px solid rgb(206, 212, 218);
  border-bottom-right-radius: 6px;
  border-bottom-left-radius: 6px;
}
```

If we remove the `max-height` then the page doesn't jump to the bottom of the editor's visible area when contents exceed the editor's height but we'd like to keep the editors the same height regardless of their content. 

You can kind of see it here as well, but it only jumps to the bottom once so it's not as egregious as our screenshot: https://codesandbox.io/embed/throbbing-morning-m1jnr7?fontsize=14&hidenavigation=1&theme=dark  

I don't think it should jump at all if the textbox is completely in view.

## The current behavior
When editing and the content exceeds the max-height defined in the CSS and the scrollbar appears in the editor, the page's scrollbar jumps to the bottom of the editor's visible area even if the editor's completely in view

## The expected behavior
When editing and the content exceeds the max-height defined in the CSS, the scrollbar appears in the editor only as the editor's is already completely in view
