### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by jvithlani** [facebook/lexical#7554]
Lexical version: 0.31.2

## Steps To Reproduce

1. Add a checklist
2. increase the font size

## The current behavior:
On increasing the font size the size of the checkbox remains unchanged.
<img width="1241" alt="Image" src="https://github.com/user-attachments/assets/70df3fe8-610b-47d4-a451-206581865262" />

## The expected behavior:
On increasing the font size the size of the checkbox also matches the font

<img width="938" alt="Image" src="https://github.com/user-attachments/assets/1d02cf6d-6c99-4671-b3c0-f68f8de9b977" />

## Impact of fix
This fixes the overall checklist UX

**Comment by etrepum** [comment]
This should be a straightforward CSS addition, the same sort of styles that apply to the marker should be applied to the checkbox input.

```css
.PlaygroundEditorTheme__listItem::marker {
  color: var(--listitem-marker-color);
  background-color: var(--listitem-marker-background-color);
  font-family: var(--listitem-marker-font-family);
  font-size: var(--listitem-marker-font-size);
}
```
